export const ActionTypes = {
  SET_DATA: 'SET_DATA',
  SET_LOADING: 'SET_LOADING',
  FETCH_TRENDINGS: 'FETCH_TRENDINGS',
  SET_SEARCH_LOADING: 'SET_SEARCH_LOADING',
  SET_SEARCH_DATA: 'SET_SEARCH_DATA',
  CLEAR_SEARCH_DATA: 'CLEAR_SEARCH_DATA',
  LOAD_MORE_SEARCH: 'LOAD_MORE_SEARCH',
};
